version: '3'
services:
  mariadb:
    hostname: mariadb1
    image: "mariadb:10.11"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: budgets
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - "/var/lib/mysql/data"
      - "/var/lib/mysql/logs"
      - "/var/docker/mariadb/conf:/etc/mysql"
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "/usr/local/bin/healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
      interval: 5s
      timeout: 3s
      retries: 2
  flyway:
    image: flyway/flyway:10-alpine
    command: -url=jdbc:mariadb://mariadb1:3306/budgets  -user=user -password=password migrate
    volumes:
      - ./migrations:/flyway/sql
    depends_on:
      mariadb:
        condition: service_healthy